### ISSUE TITLE
How can I train this model on the custom dataset in Google Colab?

### ISSUE THREAD

**Issue by RahaAghaei** [giuliomattolin/ConfMix#10]
How can I train this model on the custom dataset in Google Colab?

**Comment by giuliomattolin** [comment]
Hi @RahaAghaei,

To use our method in Google Colab you can simply clone the directory there and create a custom .yaml file in the folder `data`, where you need to specify the correct paths to your data. After that, you can follow the procedure explained in the README of the repo and adapt the model on your custom data.

I tried and everything works correctly. However, it may appen that due to an incompatibility between the PyTorch version installed in Colab and the version of YOLOv5 we used, you get the error *RuntimeError: result type Float can't be cast to the desired output type long int* in the `utils/loss.py` file. As explained in https://github.com/ultralytics/yolov5/issues/8405, this can be fixed by modifying line 186 from 
https://github.com/giuliomattolin/ConfMix/blob/f4c0ef3c385f103597537e8b4d7624601732b2b3/utils/loss.py#L186
to `gain = torch.ones(7, device=self.device).long()`

I hope this will help you.

**Comment by mytkmas** [comment]
Hello, thank you for the code you wrote and support it. My problem is different.
I set the code according to the instructions for my data, but when I run it in phase 1, I get the following error:

File "/content/ConfMix/train.py", line 238, in train
assert mlc < nc, f'Label class {mlc} exceeds nc={nc} in {data}. Possible class labels are 0-{nc - 1}'
AssertionError: Label class flower exceeds nc=4 in /content/drive/path/my_dt.yaml. Possible class labels are 0-3

that my classes in the `.yaml` file are set as follows:
nc: 4
name: ['flower', 'plant', 'stem', 'leaf']

Even if I delete the data of the class that gives an error, it gives this error on the other class.

**Comment by giuliomattolin** [comment]
Hi @mytkmas,

The problem you are facing is probably because the class labels in your annotations are not zero-indexed. If you are training on 4 classes your class labels should be for example: 0 for flower, 1 for plant, 2 for stem, and 3 for leaf. Check that this condition is met, you get the error because this condition is violated.

Regarding the other questions, you can use the same .yaml file for each phase. You can have a look at the file that we used (e.g. `data/Cityscapes2Foggy.yaml`) and structure your .yaml file similarly.

**Comment by mytkmas** [comment]
**Thank you very much for your response.**
Is the general process of your work like this, if not, please tell me the mistake?

-You have first trained in **phase 1** on `Cityscapes2Foggy.yaml` data with **default YOLO weights**.
-In the **phase 2**, you have trained again on the same before data, but this time with the weights trained from the previous data.
-And in the **Evaluation** section, you used the weights obtained in the second phase to evaluate the entire model.

**Now my question is here?** In the `.yaml` file in phase 1, the data were labeled, and in the second phase, in addition to the data in the training section, in the **uad** section in `.yaml ` file, this time, the **uda** data is separated from the first phase data and without labels?

**Comment by RahaAghaei** [comment]
Hi, I wanted to run the uda_train section, but I get the following error.
AssertionError: uda: No labels in /content/drive/MyDrive/Deep Learning/train_dataset/real.cache. Can't train without labels. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

Shouldn't we put unlabeled data in the uda part of our target dataset?
