### ISSUE TITLE
Port method to YOLOv7

### ISSUE THREAD

**Issue by yycweng** [giuliomattolin/ConfMix#16]
I tried to port the ConfMix method to YOLOv7, but the results were significantly different from YOLOv5. Is this because the network structure of YOLOv7 has changed? Hope you can give me some advice!

**Comment by giuliomattolin** [comment]
Hi @yycweng,

Unfortunately, I am not up to date on the changes made in YOLOv7 in terms of network architecture and code. I can only advise you to change only the network architecture and make sure that the code you use is as similar as possible to ConfMix, in order to avoid potential bugs or unwanted dissimilarities.

**Comment by cduej** [comment]
> I tried to port the ConfMix method to YOLOv7, but the results were significantly different from YOLOv5. Is this because the network structure of YOLOv7 has changed? Hope you can give me some advice!
I also met a similar problem, may I ask you to communicate with me.
