### ISSUE TITLE
mAP Reproducibility

### ISSUE THREAD

**Issue by qwedaq** [giuliomattolin/ConfMix#24]
Greetings

I have followed all the commands mentioned in the readme to download the dataset and train the model using the provided commands in two phases. I ran three trials for each of the experiments. I have observed the following variability in the metric mAP 0.5. I am also attaching their wandb logs.

*Exp: Sim10k to Cityscapes (Car only)*
Trial 1: 54.3
Trial 2: 53.7
Trial 3: 51.8
![sim2city](https://github.com/giuliomattolin/ConfMix/assets/25226325/3441091e-e4eb-4ca1-91de-41fceb862467)

*Exp: Cityscapes to Foggy Cityscapes (8 classes)*
Trial 1: 38.2
Trial 2: 37.3
Trail 3: 36.8
![city2foggy](https://github.com/giuliomattolin/ConfMix/assets/25226325/8698c88b-959d-4d09-b2a5-9c549a006aa3)

Is this variation expected?

**Comment by giuliomattolin** [comment]
Hi @qwedaq,

Thank you for reporting these results. Unfortunately, these behaviors could be caused by different factors that cannot always be determined, this topic has already been discussed https://github.com/giuliomattolin/ConfMix/issues/23 if you're interested. One thing that I find intriguing in both your results and the results reported in https://github.com/giuliomattolin/ConfMix/issues/23, is that the more runs are made the lower the mAP score tends to be.
